title: Erick Maina
logo: "WhatsApp Image 2020-02-05 at 11.03.23.jpeg?raw=true"
description: >
  Developer
  <br><br>
  I am a Fourth year student at Kenyatta University studying Information Technology,
  My focus areas include android development, full stack web development, data analysis and  machine learning. 
  <br><br>
  <a href="https://linkedin.com/in/eric-nit-b154a0193">View My LinkedIn Profile</a>

theme: jekyll-theme-slate
